### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by ardimasp** [CristovalNS/FSM_Virtual_Final_Project#1]
Yours is the best I've seen so far. However, it needs a minor revision. Could you please make your simulation continuously run (not one-time run only)?  Other parts that need to be fixed are very minor such that the UX of your simulator (It's minor tho). Please revise it accordingly by the 11th of Jan 2023. Thanks!!!

**Comment by CristovalNS** [comment]
Alright Sir, thank you ^_^

**Comment by CristovalNS** [comment]
I've updated the code to run indefinitely until the user quit the program. The code will also retain the Floor_lvl state. The user won't have to redeclare the Floor_lvl state over and over again, simulating the elevator system better.

**Comment by ardimasp** [comment]
Thanks. I have accepted it. Many thanks for your hard work
